const tintColor = '#2f95dc';

export default {
  tintColor,
  tabIconDefault: '#ccc',
  tabIconSelected: tintColor,
  tabBar: '#fefefe',
  errorBackground: 'red',
  errorText: '#fff',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: tintColor,
  noticeText: '#fff',
  redPrimary: "#f44336",
  orangePrimary: "#FF9800",
  yellowPrimary: "#FFEB3B",
  limePrimary: "#CDDC39",
  greenPrimary: "#4CAF50",
  bluePrimary: "#2196F3",
  purplePrimary: "#9C27B0",
  indigoPrimary: "#3F51B5",
  redMuted: "#ffcdd2",
  orangeMuted: "#FFE0B2",
  yellowMuted: "#FFF9C4",
  limeMuted: "#F0F4C3",
  greenMuted: "#C8E6C9",
  blueMuted: "#BBDEFB",
  purpleMuted: "#E1BEE7",
  indigoMuted: "#C5CAE9",
};
